version: '3'
services:
  app:
    restart: always
    env_file: 
      - .env-local
    environment:
      - "DJANGO_SETTINGS_PROFILE=local"
    build: .
    ports:
      - "5005:5005"
    networks:
      - int_network
    depends_on: 
      - database
      - sessions
      - migration

  migration:
    restart: "no"
    env_file: 
      - .env-local
    environment:
      - "DJANGO_SETTINGS_PROFILE=local"
    build: .
    entrypoint: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate"]    
    networks:
      - int_network
    depends_on: 
      - database
    
  lb:
    restart: always
    image: "nginx:1.19.3"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - ext_network
      - int_network
    depends_on: 
      - app

  database:
    restart: always
    env_file: 
      - .env-local
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password    
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - int_network

  dbadm:
    image: adminer:4.7.7
    restart: always
    ports:
      - "8080:8080"
    networks:
      - int_network
    depends_on: 
      - database
  
  sessions:
    restart: always
    env_file: 
      - .env-local
    image: redis:6.0.8
    ports:
      - "6379:6379"
    volumes:
      - ./sessions:/data
    networks:
      - int_network

networks:
  int_network:
    driver: bridge
  ext_network:
    driver: bridge
